### ISSUE TITLE
missing keyword: schema (ArgumentError)

### ISSUE THREAD

**Issue by chinito** [github/graphql-client#130]
When using:

```
gem "graphql", "1.7.4"
gem "graphql-client", "0.12.1"
````

The `require "graphql/client/railtie"` fails on startup of the app.

Stacktrace:
```
/Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client.rb:87:in `initialize': missing keyword: schema (ArgumentError)
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client/railtie.rb:17:in `new'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client/railtie.rb:17:in `<class:Railtie>'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client/railtie.rb:15:in `<class:Client>'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client/railtie.rb:7:in `<module:GraphQL>'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphql-client-0.12.1/lib/graphql/client/railtie.rb:6:in `<top (required)>'
	from /Users/USERNAME/RailsApps/github-graphql-rails-example/config/application.rb:6:in `require'
	from /Users/USERNAME/RailsApps/github-graphql-rails-example/config/application.rb:6:in `<top (required)>'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /Users/USERNAME/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>' 
```

Any ideas?

**Comment by BenEmdon** [comment]
This is a problem with `graphql/client/railtie`. In that file the following line happens:
https://github.com/github/graphql-client/blob/773b8260f5af0307a5a6400e81f74e1c60261071/lib/graphql/client/railtie.rb#L17
And the problem with this is that the client initializer requires a `schema` argument. https://github.com/github/graphql-client/blob/773b8260f5af0307a5a6400e81f74e1c60261071/lib/graphql/client.rb#L87

I'll see if I can get to the source of this 👀

**Comment by benjam1n** [comment]
Hi there! 

So, I'm having the same "missing keyword: schema" problems and I fixed it by using an older version of the gem and adding erubis:

```
gem "graphql"
gem "graphql-client", "0.4.3"
gem "erubis"
```

I must confess I don't really have any idea what am I doing but it worked.

Also, I'm including some things in my application.rb, well, because it won't work otherwise:

```
require "graphql/client/railtie"
require "graphql/client/http"
```

Most importantly, I actually do have a schema.json and I'm loading it via

`GraphQL::Client.new(schema: "db/schema.json", execute: HTTPAdapter)`

Any advice how to fix this and actually use the latest version of the gem?

ps. this is on rails 5.1.5

**Comment by josh** [comment]
There's some issues with the Railtie right now. https://github.com/github/graphql-client/pull/136 should help. If you can please test that branch and leave feedback. Thanks.
