### ISSUE TITLE
`undefined method `[]'` when parsing query in graphql-ruby 2.1.0

### ISSUE THREAD

**Issue by necocoa** [github/graphql-client#310]
Parse fails when upgrading to `graphql` 2.1.0.
It is most likely a change in the Visitor hooks API that is Breaking changes.

https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#210-30-aug-2023

> Visitor: legacy-style proc-based visitors are no longer supported #4577 #4583

https://github.com/rmosolgo/graphql-ruby/pull/4577

I've written a script to demonstrate the error across two versions of the gem

```ruby
require "bundler/inline"

gemfile do
  source 'https://rubygems.org'

  if ENV["BEFORE"]
    puts "using graphql 2.0.26"
    gem "graphql-client", "0.18.0"
    gem "graphql", "2.0.26"
  elsif ENV["AFTER"]
    puts "using graphql 2.1.0"
    gem "graphql-client", "0.18.0"
    gem "graphql", "2.1.0"
  else
    raise "Pass BEFORE=1 or AFTER=1"
  end
end

class Query <  GraphQL::Schema::Object
  field :hoge, String, null: false
  def hoge
    "hoge"
  end
end

class Schema < GraphQL::Schema
  query Query
end

client = GraphQL::Client.new(schema: Schema, execute: Schema)

QUERY = client.parse(<<-'GRAPHQL')
  query {
    hoge
  }
GRAPHQL

p result.data.hoge

```

Here is the error trace that occurs.

```
/Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:28:in `add_typename': undefined method `[]' for nil:NilClass (NoMethodError)

            type = @types[node]
                         ^^^^^^
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:48:in `on_operation_definition'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:95:in `on_operation_definition_with_modifications'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:121:in `public_send'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:121:in `block in on_document_children'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:119:in `each'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:119:in `on_document_children'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:84:in `on_document'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:95:in `on_document_with_modifications'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:53:in `public_send'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.1.0/lib/graphql/language/visitor.rb:53:in `visit'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:62:in `insert_typename_fields'
        from /Users/nat/.anyenv/envs/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:189:in `parse'
        from main.rb:32:in `<main>'
```

**Comment by wuarmin** [comment]
I have the same issue.

**Comment by lednerb1** [comment]
Same

**Comment by wuarmin** [comment]
I posted a question how to solve this at https://github.com/rmosolgo/graphql-ruby/pull/4577

**Comment by LeslieCarr** [comment]
Same issue

**Comment by rmosolgo** [comment]
Yeah, we removed the deprecated visitor `[node_class] << ...` API in GraphQL-Ruby 2.1, including the internal `TypeStack` visitor. 

I started migrating those visitors in graphql-client just now and found that GraphQL-Client has other incompatibilities in its test suite: 

- `MiniTest` -> `Minitest`
- It still uses `.define`-based GraphQL definitions which have been removed since GraphQL-Ruby 
- `use GraphQL::Execution::Interpreter` needs to be removed; it's default now and can't be added that way 


Anyhow, here's an example migration: 

```diff
diff --git a/lib/graphql/client.rb b/lib/graphql/client.rb
index 83bad2d..9c3bf68 100644
--- a/lib/graphql/client.rb
+++ b/lib/graphql/client.rb
@@ -425,12 +425,26 @@ module GraphQL
       end.to_h
     end

+    class GatherNamesVisitor < GraphQL::Language::Visitor
+      def initialize(node)
+        @names = []
+        super
+      end
+
+      attr_reader :names
+
+      def on_fragment_spread(node, parent)
+        @names << node.name
+        super
+      end
+    end
+
     def find_definition_dependencies(node)
-      names = []
-      visitor = Language::Visitor.new(node)
-      visitor[Language::Nodes::FragmentSpread] << -> (node, parent) { names << node.
name }
+      visitor = GatherNamesVisitor.new(node)
       visitor.visit
-      names.uniq
+      names = visitor.names
+      names.uniq!
+      names
     end
```

There are several others that need the same treatment: 

- Migrate the `Language::Visitor` instance to a custom subclass 
- Move the `[node_class] << -> ...` hooks into `on_{node_class}` methods 
- Migrate the visitor's state to use instance variables on the custom subclass instead of local variables in the proc

**Comment by zavan** [comment]
I'm assuming https://github.com/ashkan18/graphlient has the same problem, since it's based on this gem?

**Comment by rellampec** [comment]
@zavan same problem with `graphlient`

I had set a limit to the `graphql` version in the Gemfile:

```ruby
gem "graphql",     '>= 2.0.27',  '< 2.1'
```

**Comment by tagur87** [comment]
We also are having issues using this graphql client in our chef cookbooks. Is there a fix planned for this library that we can get pushed through?

**Comment by rwstauner** [comment]
The problem with `analyze_types` is that the exception is discarded:

this raises because the constant no longer exists in the newer graphql version
https://github.com/github/graphql-client/blob/2c611765e34ded9e63085b4b40a8da59d8ce8732/lib/graphql/client/document_types.rb#L24-L26

the exception is caught here and discarded (and by that point, `fields` has not been set)
https://github.com/github/graphql-client/blob/2c611765e34ded9e63085b4b40a8da59d8ce8732/lib/graphql/client/document_types.rb#L43-L49

**Comment by rmosolgo** [comment]
CI is a bit ... dusty ... but I got several key tests to run on this branch: https://github.com/github/graphql-client/pull/314

Could someone give that a try and let me know how it goes for them? You can bundle it like this: 

```ruby 
gem "graphql-client", github: "rmosolgo/graphql-client", ref: "27ef61f"
```

I've migrated everything I could _find_, but I'm just working from the test files that I could get to run on GraphQL-Ruby 2.1 😅

**Comment by mitchpascoe** [comment]
> CI is a bit ... dusty ... but I got several key tests to run on this branch: #314
> 
> Could someone give that a try and let me know how it goes for them? You can bundle it like this:
> 
> ```ruby
> gem "graphql-client", github: "rmosolgo/graphql-client", ref: "27ef61f"
> ```
> 
> I've migrated everything I could _find_, but I'm just working from the test files that I could get to run on GraphQL-Ruby 2.1 😅

Haven't tested further than locally and in CI but this looks to be working well so far @rmosolgo, thanks!

**Comment by rchasman** [comment]
Same as Mitch. All appears well updating graphql-ruby alongside this patch. @rmosolgo, thank you 🙏

**Comment by rmosolgo** [comment]
Thanks for taking a look , I'll see what I can do to get that patch released!

**Comment by quentin** [comment]
When I print `err` here:

https://github.com/github/graphql-client/blob/2c611765e34ded9e63085b4b40a8da59d8ce8732/lib/graphql/client/document_types.rb#L43-L49

I get this exception: `<NameError: uninitialized constant GraphQL::StaticValidation::TypeStack>`

It seems that definition of `TypeStack` is missing in this file. Maybe a missing `require` somewhere?

**Comment by billybonks** [comment]
@rmosolgo patch works for me as well. Hopefully github will respond soon, thanks for the effort.

**Comment by rmosolgo** [comment]
👋  @arthurschreiber Happy new year! A lot of people are stuck on this, and I'd like to get a new version on rubygems one way or another. If you (or anyone else at github?) want to keep this repo going forward, could you please merge my patch and cut a new version, or give me commit access to this repo? Otherwise I'll investigate options to publish a fork somehow, just to keep things moving.

**Comment by crpahl** [comment]
Same issue here as well. Just adding on as we're really hoping this can be resolved soon 🙏

**Comment by bmulholland** [comment]
Is it perhaps worth trying to email some of the contributors? Seems pretty clear they don't monitor this repo on github

**Comment by rmosolgo** [comment]
0.19.0 was shipped to rubygems (from github-community-projects/graphql-client) 🚢  

I'm told that the folks at GitHub are going to archive this repository and we'll use that other one from now on. 

If you update to that version and run into any more trouble, please open an issue over there!

**Comment by necocoa** [comment]
Thanks for releasing it!
