### ISSUE TITLE
Fragment spreads have trouble sometimes

### ISSUE THREAD

**Issue by nakajima** [github/graphql-client#99]
I think this is related to https://github.com/github/graphql-client/blob/master/lib/graphql/client/query_result.rb#L59.

I wrote a basic test in https://github.com/github/graphql-client/commit/dd58f02d0d92606defe003d9c2e9afc2874e0e71.

**Comment by josh** [comment]
You need to cast `response.data.current_actor` to a `Query::Person`.

``` ruby
actor = Query::Person.new(response.data.current_actor)
actor.name
```

**Comment by nakajima** [comment]
The trouble I'm seeing is that given the following code:

```rb
Temp.const_set :Query, @client.parse(<<-'GRAPHQL')
  fragment Person on Person {
    name
  }

  query {
    currentActor {
      ...Person
    }
  }
GRAPHQL
```

The `Query::Person` constant doesn't exist. If we define it on its own, it works:

```rb
Temp.const_set :Person, @client.parse(<<-'GRAPHQL')
  fragment Person on Person {
    name
  }
GRAPHQL

Temp.const_set :Query, @client.parse(<<-'GRAPHQL')
  query {
    currentActor {
      ...TestQueryResult::Temp::Person::Person
    }
  }
GRAPHQL

response = @client.query(Temp::Query)
actor = TestQueryResult::Temp::Person::Person.new(response.data.current_actor)

assert_equal "Josh", actor.name
```

I'd expect a fragment defined in the same query to also work.

**Comment by josh** [comment]
```
Temp.const_set :Query, @client.parse(<<-'GRAPHQL')
  fragment Person on Person {
    name
  }

  query {
    currentActor {
      ...Person
    }
  }
GRAPHQL
```

I'm surprised this doesn't raise an error on parse. In the case of multiple definitions, its supposed to return a `module`, but here `query` has no name.

```
Temp.const_set :Doc, @client.parse(<<-'GRAPHQL')
  fragment Person on Person {
    name
  }

  query Query {
    currentActor {
      ...Person
    }
  }
GRAPHQL
```

I think if you did that `Doc::Query` and `Doc::Person` should be exported.

**Comment by nakajima** [comment]
Yup, the constants get set properly when giving both parts names:

```rb
Temp.const_set :Doc, @client.parse(<<-'GRAPHQL')
  fragment Person on Person {
    name
  }

  query Query {
    currentActor {
      ...Person
    }
  }
GRAPHQL

response = @client.query(Temp::Doc::Query)
actor = Temp::Doc::Person.new(response.data.currentActor)
assert_equal "Josh", actor.name
```

This still fails though:

```rb
response = @client.query(Temp::Doc::Query)
data = Temp::Doc::Query.new(response.data)
assert_equal "Josh", data.currentActor.name
```

At very least, I think we should look at making this error more helpful:

```
1) Error:
TestQueryResult#test_interfaces_allow_fragments_from_types_that_implement_them:
NoMethodError: undefined method `all_fields' for Actor:GraphQL::UnionType
  /Users/douglasnakajima/github/graphql-client/lib/graphql/client/query_result.rb:385:in `rescue in method_missing'
  /Users/douglasnakajima/github/graphql-client/lib/graphql/client/query_result.rb:380:in `method_missing'
  /Users/douglasnakajima/github/graphql-client/test/test_query_result.rb:525:in `test_interfaces_allow_fragments_from_types_that_implement_them'
```

But I'd expect the spread to just work without a need to recast here.

**Comment by josh** [comment]
This will probably have to be something that gets fixed in the new schema generation branch. Right now everything around merging `Union`s or `Interface` types is horribly broken.

**Comment by josh** [comment]
Obsoleted by #104 proposal.
